### PR TITLE
Updates to the e2e queries - Kibana 7(.10.2)

### PR DESCRIPTION
**Pull request by eladiw**
The following changes are proposed:

* Kept the same logic in the queries but with the new format of Kibana 7

### CODE REVIEW

**Review by tomconte — COMMENTED** [review]
Should we have a mix of fixed_interval and calendar_interval in the queries so we cover both cases?

**Review by tomconte — APPROVED** [review]
Looks good to me!

**Comment by AsafMah** [comment]
How did you do these changes? 
Manually? Find + replace? some tool?

**Comment by eladiw** [comment]
no. captured new queries.
one note: the timestamps are manual because I wanted it to be identical.

**Pull request merged**
