### PR TITLE
Changing latest image tag to 7.10_latest

### PR DESCRIPTION
**Pull request by eladiw**
The following changes are proposed:

* Changing latest image tag to 7.10_latest

### CODE REVIEW

**Review by YannickBrombach — APPROVED** [review]
lgtm

**Review by YannickBrombach — COMMENTED** [review]
Just checking, is it the right ES version to use?

**Comment by eladiw** [comment]
@YannickBrombach  , yes the ES is the correct version (maybe we can upgrade to 7.10, on another pr)

**Review by tamirkamara — APPROVED** [review]

**Review by AsafMah — APPROVED** [review]

**Pull request merged**
