### PR TITLE
Changing latest image tag to 6.8_latest

### PR DESCRIPTION
**Pull request by eladiw**
The following changes are proposed:

* Changing latest image tag to 6.8_latest
* Following PR will change the new version to 7.10_latest

### CODE REVIEW

**Review by tomconte — APPROVED** [review]

**Review by AsafMah — APPROVED** [review]
lgtm

**Review by YannickBrombach — COMMENTED** [review]
Same comment that on the 7.1 pr, is that the right version?

**Comment by eladiw** [comment]
> Same comment that on the 7.1 pr, is that the right version?

yes. it supports es 6.8 (was not changed recently)

**Review by tamirkamara — APPROVED** [review]

**Pull request merged**
