### PR TITLE
CI - Fail on low code coverage (threshold set to 79%)

### PR DESCRIPTION
**Pull request by eladiw**
The following changes are proposed:

* Added a code build quality task
* https://marketplace.visualstudio.com/items?itemName=mspremier.BuildQualityChecks#task-parameters
* https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/CodeCoveragePolicy.md
* Set threshold to 79%

### CODE REVIEW

**Comment by YannickBrombach** [comment]
Love it, let’s discuss some more during our next standup about code quality

**Review by YannickBrombach — APPROVED** [review]
Ahah, looking good :)

**Comment by AsafMah** [comment]
Did you choose 78.9 because that's where we are right now?

**Comment by eladiw** [comment]
@AsafMah  yes

**Review by AsafMah — APPROVED** [review]
Personally I'm not a big fan of hard code coverage limitations, but if that's what the team wants it looks good.
Maybe we want to at least put it at 75% to have some wiggle room

**Comment by eladiw** [comment]
@AsafMah  you can configure it for more dynamic values, e.g. to have at least coverage as previous build.
lets discuss f2f

**Pull request merged**
